#cloud-config
# ^-- This line is required for this to work on AWS with Ubuntu!
#
# cloud-init for multipass on x86 or arm64
# multipass launch -d 80G -c 4 -m 12G --cloud-init https://cenkalti.com/cloud-init.yaml -n go-dev

apt:
    preserve_sources_list: true
    sources:
        golang-ppa:
            source: "ppa:longsleep/golang-backports"
        gh:
            source: "deb https://cli.github.com/packages stable main"
            keyid: 23F3D4EA75716059
        docker:
          source: "deb https://download.docker.com/linux/ubuntu $RELEASE stable"
          keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true
package_upgrade: true
packages:
    - git
    - make
    - jq
    - vim
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - golang
    - gh
    - unzip
    - python3-pip
    - zsh

users:
    - default
    - name: cenk
      primary_group: cenk
      groups: users, docker
      shell: /usr/bin/zsh
      sudo: ALL=(ALL) NOPASSWD:ALL
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGzNAlGIuabAr7UkqAzveXgIWFSGk7Lq4r0LHeUtN9hP atolio

runcmd:
    - |
      cd /home/cenk
      ssh-keygen -R github.com
      curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> /home/cenk/.ssh/known_hosts
      mkdir bin
      echo 'export PATH=$HOME/bin:$HOME/go/bin:$PATH' >>.bash_profile
      echo 'export PATH=$HOME/bin:$HOME/go/bin:$PATH' >>.bashrc

    - pip3 install aws2-wrap

    - |
      # Install golang-ci
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

    - |
      # install AWS CLI
      cd /tmp
      bash -c 'curl -o awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip'
      unzip awscliv2.zip
      ./aws/install

final_message: "The system is finally up, after $UPTIME seconds"
